# Generated by Django 5.0.3 on 2024-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verfication_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
