# Generated by Django 5.0.3 on 2024-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_verfication_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_link',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
