# Generated by Django 5.0.4 on 2024-04-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='HEL80BESYYZEYZGH', max_length=16, primary_key=True, serialize=False)),
                ('message_content', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('update', 'Update'), ('reminder', 'Reminder')], max_length=20, null=True)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), (' delivered', 'Delivered'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documetn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
