# Generated by Django 5.0.6 on 2024-05-11 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicel',
            fields=[
                ('id', models.CharField(default='d4e8846d8b024b17', max_length=16, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=32, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
