# Generated by Django 5.0.4 on 2024-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel',
            name='id',
            field=models.CharField(default='DJFWNRQDZIFCB2LF', max_length=16, primary_key=True, serialize=False),
        ),
    ]
