# Generated by Django 5.0.6 on 2024-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel',
            name='id',
            field=models.CharField(default='bc58567ded0e4c9a', max_length=16, primary_key=True, serialize=False),
        ),
    ]
