# Generated by Django 5.0.6 on 2024-05-15 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicel_plate_number_alter_vehicel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
