# Generated by Django 5.0.4 on 2024-04-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Third party insurance', 'third_party_insurance'), ('Road fund', 'road_fund'), ('Road Authority', 'road_authority'), ('Bolo', 'bolo')], max_length=100)),
                ('renewal_status', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('files', models.ManyToManyField(to='files.files')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicel')),
            ],
        ),
    ]
