# Generated by Django 5.0.4 on 2024-04-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0004_alter_files_id'),
        ('vehicle', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default='Y78FJQFDYTI2IKOO', max_length=16, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Third party insurance', 'Third party insurance'), ('Road fund', 'Road Fund'), ('Road Authority', 'Road Authority'), ('Bolo', 'Bolo')], max_length=100)),
                ('renewal_status', models.BooleanField(default=False)),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('files', models.ManyToManyField(blank=True, to='files.files')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicel')),
            ],
        ),
    ]
