# Generated by Django 5.0.4 on 2024-04-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Third party insurance', 'Third party insurance'), ('Road fund', 'Road Fund'), ('Road Authority', 'Road Authority'), ('Bolo', 'Bolo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.files'),
        ),
    ]
