# Generated by Django 5.0.6 on 2024-05-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='insurance_company_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
