# Generated by Django 5.0.4 on 2024-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_type_alter_document_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(default='Ek2yEgyfignAbikcsRebvQ', max_length=16, primary_key=True, serialize=False),
        ),
    ]
