# Generated by Django 5.0.6 on 2024-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.CharField(default='f22fbbaaf94e4772', max_length=16, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_address', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
