# Generated by Django 5.0.4 on 2024-04-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_address', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
