# Generated by Django 5.0.4 on 2024-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='VVXAUZKB1R7X4OA0', max_length=16, primary_key=True, serialize=False),
        ),
    ]
