# Generated by Django 5.0.4 on 2024-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='LXS1TG6L1EKRLGG1', max_length=16, primary_key=True, serialize=False),
        ),
    ]
