# Generated by Django 5.0.4 on 2024-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_files_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.CharField(default='6B46ZISMWS2YLI1T', max_length=16, primary_key=True, serialize=False),
        ),
    ]
